CREATE DATABASE MUSIC_SELECTOR;
USE MUSIC_SELECTOR;

CREATE TABLE tracks(
ID INTEGER PRIMARY KEY,
TITLE VARCHAR(225),
PRODUCED_BY VARCHAR(225),
LANG_ID INTEGER,
MOOD_ID INTEGER,
ERA_ID INTEGER
);

CREATE TABLE directory(
ID INTEGER PRIMARY KEY,
TITLE VARCHAR(225),
PRODUCED_BY VARCHAR(225),
LANG VARCHAR(225),
MOOD VARCHAR(225),
ERA VARCHAR(225)
);


